version: '3.1'
services:
  app:
    build:
      context: "$PWD"
      dockerfile: Dockerfile
    volumes:
     - ./:/mnt/
    ports:
     - 800:3000
    restart: always
    tty: true
    stdin_open: true
